name: Generate Low-Level Snake Animation
on:
  # Executa automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite executar manualmente
  workflow_dispatch:

  # Executa em todo push na branch main
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Gera arquivos da snake
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: silvaluzb
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-terminal.svg?palette=terminal
            dist/github-contribution-grid-snake-assembly.svg?palette=assembly
            dist/github-contribution-grid-snake-memory.svg?palette=memory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Push dos arquivos gerados
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
